import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Navbar} from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { getOptionalSession } from "@/lib/dal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await getOptionalSession();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar user={session ? { name: session.name, role: session.role } : null}></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
